[package]
name = "pi-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop = "0.20.2"
lalrpop-util = "0.20.2"
log = "0.4.21"

[lib]
doctest = false

[build-dependencies]
lalrpop = "0.20.2"
